DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)      NOT NULL,
    annotation         VARCHAR(2000)     NOT NULL,
    description        TEXT              NOT NULL,
    category_id        BIGINT            NOT NULL,
    initiator_id       BIGINT            NOT NULL,
    event_date         TIMESTAMP         NOT NULL,
    created_on         TIMESTAMP         NOT NULL DEFAULT NOW(),
    published_on       TIMESTAMP,
    paid               BOOLEAN           NOT NULL DEFAULT FALSE,
    participant_limit  INTEGER           NOT NULL DEFAULT 0,
    request_moderation BOOLEAN           NOT NULL DEFAULT TRUE,
    state              VARCHAR(50)       NOT NULL,
    lat       DOUBLE PRECISION,
    lon       DOUBLE PRECISION
);

ALTER TABLE events
    ADD CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES categories(id);

ALTER TABLE events
    ADD CONSTRAINT fk_events_initiator FOREIGN KEY (initiator_id) REFERENCES users(id);