CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);



CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)      NOT NULL,
    annotation         VARCHAR(2000)     NOT NULL,
    description        TEXT              NOT NULL,
    category_id        BIGINT            NOT NULL REFERENCES categories(id),
    initiator_id       BIGINT            NOT NULL REFERENCES users(id),
    event_date         TIMESTAMP         NOT NULL,
    created_on         TIMESTAMP         NOT NULL DEFAULT NOW(),
    published_on       TIMESTAMP,
    paid               BOOLEAN           NOT NULL DEFAULT FALSE,
    participant_limit  INTEGER           NOT NULL DEFAULT 0,
    request_moderation BOOLEAN           NOT NULL DEFAULT TRUE,
    state              VARCHAR(50)       NOT NULL,
    lat       DOUBLE PRECISION,
    lon       DOUBLE PRECISION
);
);